In [12]:
import pandas as pd

In [96]:
# ls

In [4]:
import os
from datetime import datetime

# Считывание данных

Из названий фотографий возможно получить статистику по времени, в которое был произведён снимок. Оценить время года, временной промежуток, день когда возникает больше всего проблем с вывозом.

In [30]:
dates=[]
l=[]
path='trash/0'
with os.scandir(path) as it:
    for entry in it:
#         print(entry.name)
        if entry.name.endswith(".txt"):
            l+=[entry.path]
            dates+=[[path[-1:], entry.name, datetime.strptime(entry.name[:-4],'%d-%m-%Y_%I-%M-%S_%p')]]
#             dates.append(pd.to_datetime(datetime.strptime(entry.name[:-4],'%d-%m-%Y_%I-%M-%S_%p')))
#             dates.append(pd.to_datetime(entry.name[:-4],format='%d-%m-%Y_%I-%M-%S_%p').to_pydatetime,sort=False)
#             print(path[-1:], datetime.strptime(entry.name[:-4],'%d-%m-%Y_%I-%M-%S_%p'))
dates[:5]

[['0',
  '23-11-2021_02-36-28_PM.txt',
  datetime.datetime(2021, 11, 23, 14, 36, 28)],
 ['0',
  '23-11-2021_03-48-02_PM.txt',
  datetime.datetime(2021, 11, 23, 15, 48, 2)],
 ['0',
  '23-11-2021_07-22-30_PM.txt',
  datetime.datetime(2021, 11, 23, 19, 22, 30)],
 ['0',
  '23-11-2021_07-40-28_PM.txt',
  datetime.datetime(2021, 11, 23, 19, 40, 28)],
 ['0',
  '23-11-2021_08-33-54_PM.txt',
  datetime.datetime(2021, 11, 23, 20, 33, 54)]]

In [36]:
dates_df=pd.DataFrame(dates, columns=['folder','filename','timestamp'])
dates_df[:5]

  folder                    filename           timestamp
0      0  23-11-2021_02-36-28_PM.txt 2021-11-23 14:36:28
1      0  23-11-2021_03-48-02_PM.txt 2021-11-23 15:48:02
2      0  23-11-2021_07-22-30_PM.txt 2021-11-23 19:22:30
3      0  23-11-2021_07-40-28_PM.txt 2021-11-23 19:40:28
4      0  23-11-2021_08-33-54_PM.txt 2021-11-23 20:33:54

In [73]:
dates_df['filename'].unique().size

50

In [56]:
l[:5]

['trash/0\\23-11-2021_02-36-28_PM.txt',
 'trash/0\\23-11-2021_03-48-02_PM.txt',
 'trash/0\\23-11-2021_07-22-30_PM.txt',
 'trash/0\\23-11-2021_07-40-28_PM.txt',
 'trash/0\\23-11-2021_08-33-54_PM.txt']

# Время из имени файла

In [12]:
info=pd.DataFrame(columns=[])

In [45]:
with open("test.txt", "a") as myfile:
    for i in range(len(l)):
        with open(''.join(l[0]), 'r' ) as result:
            for line in result:
#                            [папка, название, данные . . . . .]
                myfile.write(str(l[i][8:]) + ' ' + line+ '\n')
        
        
#         with open(filename) as file:
#     lines = file.readlines()
#     lines = [line.rstrip() for line in lines]

# Обработка текстовой информации о мусоре

In [79]:
df=pd.read_csv('test.txt', 
               sep=' ',
               header=None, 
               names=['filename','bool','centerX','centerY','width','height']
              )
df

                      filename  bool   centerX   centerY     width    height
0   23-11-2021_02-36-28_PM.txt     0  0.530682  0.588856  0.032708  0.064176
1   23-11-2021_02-36-28_PM.txt     0  0.611716  0.591657  0.032464  0.074074
2   23-11-2021_03-48-02_PM.txt     0  0.530682  0.588856  0.032708  0.064176
3   23-11-2021_03-48-02_PM.txt     0  0.611716  0.591657  0.032464  0.074074
4   23-11-2021_07-22-30_PM.txt     0  0.530682  0.588856  0.032708  0.064176
..                         ...   ...       ...       ...       ...       ...
95  26-11-2021_10-09-00_AM.txt     0  0.611716  0.591657  0.032464  0.074074
96  26-11-2021_11-11-21_AM.txt     0  0.530682  0.588856  0.032708  0.064176
97  26-11-2021_11-11-21_AM.txt     0  0.611716  0.591657  0.032464  0.074074
98  26-11-2021_12-18-39_AM.txt     0  0.530682  0.588856  0.032708  0.064176
99  26-11-2021_12-18-39_AM.txt     0  0.611716  0.591657  0.032464  0.074074

[100 rows x 6 columns]

In [83]:
(df.filename.unique() == dates_df.filename.unique()).all()

True

In [78]:
df.groupby('filename').count()

                            bool  centerX  centerY  width  height
filename
23-11-2021_02-36-28_PM.txt     2        2        2      2       2
23-11-2021_03-48-02_PM.txt     2        2        2      2       2
23-11-2021_07-22-30_PM.txt     2        2        2      2       2
23-11-2021_07-40-28_PM.txt     2        2        2      2       2
23-11-2021_08-33-54_PM.txt     2        2        2      2       2
23-11-2021_08-51-42_PM.txt     2        2        2      2       2
24-11-2021_02-23-45_PM.txt     2        2        2      2       2
24-11-2021_02-30-41_AM.txt     2        2        2      2       2
24-11-2021_02-48-25_AM.txt     2        2        2      2       2
24-11-2021_03-16-56_PM.txt     2        2        2      2       2
24-11-2021_03-59-43_AM.txt     2        2        2      2       2
24-11-2021_04-17-33_AM.txt     2        2        2      2       2
24-11-2021_04-46-00_PM.txt     2        2        2      2       2
24-11-2021_05-11-08_AM.txt     2        2        2      2       2
24-11-2021_06-40-16_AM.txt     2        2        2      2       2
24-11-2021_06-58-08_AM.txt     2        2        2      2       2
24-11-2021_07-26-03_PM.txt     2        2        2      2       2
24-11-2021_07-51-37_AM.txt     2        2        2      2       2
24-11-2021_08-27-23_AM.txt     2        2        2      2       2
24-11-2021_09-56-20_AM.txt     2        2        2      2       2
24-11-2021_10-42-13_PM.txt     2        2        2      2       2
24-11-2021_11-00-03_PM.txt     2        2        2      2       2
24-11-2021_11-25-22_AM.txt     2        2        2      2       2
24-11-2021_11-43-12_AM.txt     2        2        2      2       2
24-11-2021_11-53-29_PM.txt     2        2        2      2       2
24-11-2021_12-54-33_PM.txt     2        2        2      2       2
25-11-2021_01-36-08_PM.txt     2        2        2      2       2
25-11-2021_01-54-03_PM.txt     2        2        2      2       2
25-11-2021_02-47-43_PM.txt     2        2        2      2       2
25-11-2021_04-33-14_PM.txt     2        2        2      2       2
25-11-2021_05-09-02_PM.txt     2        2        2      2       2
25-11-2021_05-44-58_PM.txt     2        2        2      2       2
25-11-2021_07-02-18_AM.txt     2        2        2      2       2
25-11-2021_07-32-07_PM.txt     2        2        2      2       2
25-11-2021_09-07-41_AM.txt     2        2        2      2       2
25-11-2021_09-19-35_PM.txt     2        2        2      2       2
25-11-2021_09-43-35_AM.txt     2        2        2      2       2
25-11-2021_10-31-14_PM.txt     2        2        2      2       2
25-11-2021_11-13-10_AM.txt     2        2        2      2       2
26-11-2021_01-29-57_AM.txt     2        2        2      2       2
26-11-2021_02-59-18_AM.txt     2        2        2      2       2
26-11-2021_03-35-10_AM.txt     2        2        2      2       2
26-11-2021_05-04-10_AM.txt     2        2        2      2       2
26-11-2021_05-58-09_AM.txt     2        2        2      2       2
26-11-2021_06-51-55_AM.txt     2        2        2      2       2
26-11-2021_08-21-30_AM.txt     2        2        2      2       2
26-11-2021_08-39-22_AM.txt     2        2        2      2       2
26-11-2021_10-09-00_AM.txt     2        2        2      2       2
26-11-2021_11-11-21_AM.txt     2        2        2      2       2
26-11-2021_12-18-39_AM.txt     2        2        2      2       2

In [64]:
df1= df.set_index('filename').join(dates_df.set_index('filename'),how='outer')
# df1.groupby('filename').count()
# df.size
df1.size

700

In [88]:
zero=pd.DataFrame(dates,columns=['camera','time'])

In [68]:
import matplotlib.pyplot as plt

In [97]:
# e1= pd.to_datetime(f,errors='coerce')
# plt.figure(dpi=300,figsize=(16, 8)) #A4 (11.69,8.27)
# plt.plot_date(e1.date,e1.time)
# axes=plt.gca()
# plt.gcf().autofmt_xdate()
# plt.gca().invert_yaxis()

In [91]:
zero['time'].dt.date

0     2021-11-23
1     2021-11-23
2     2021-11-23
3     2021-11-23
4     2021-11-23
5     2021-11-23
6     2021-11-24
7     2021-11-24
8     2021-11-24
9     2021-11-24
10    2021-11-24
11    2021-11-24
12    2021-11-24
13    2021-11-24
14    2021-11-24
15    2021-11-24
16    2021-11-24
17    2021-11-24
18    2021-11-24
19    2021-11-24
20    2021-11-24
21    2021-11-24
22    2021-11-24
23    2021-11-24
24    2021-11-24
25    2021-11-24
26    2021-11-25
27    2021-11-25
28    2021-11-25
29    2021-11-25
30    2021-11-25
31    2021-11-25
32    2021-11-25
33    2021-11-25
34    2021-11-25
35    2021-11-25
36    2021-11-25
37    2021-11-25
38    2021-11-25
39    2021-11-26
40    2021-11-26
41    2021-11-26
42    2021-11-26
43    2021-11-26
44    2021-11-26
45    2021-11-26
46    2021-11-26
47    2021-11-26
48    2021-11-26
49    2021-11-26
Name: time, dtype: object

In [73]:
dates[0][1].time()

datetime.time(14, 36, 28)

# Проверка для другой папки.

In [84]:
dates=[]
l=[]
path='trash/1'
with os.scandir(path) as it:
    for entry in it:
#         print(entry.name)
        if entry.name.endswith(".txt"):
            l+=[entry.path]
            dates+=[[path[-1:], entry.name, datetime.strptime(entry.name[:-4],'%d-%m-%Y_%I-%M-%S_%p')]]
#             dates.append(pd.to_datetime(datetime.strptime(entry.name[:-4],'%d-%m-%Y_%I-%M-%S_%p')))
#             dates.append(pd.to_datetime(entry.name[:-4],format='%d-%m-%Y_%I-%M-%S_%p').to_pydatetime,sort=False)
#             print(path[-1:], datetime.strptime(entry.name[:-4],'%d-%m-%Y_%I-%M-%S_%p'))
dates[:5]

[['1',
  '23-11-2021_06-11-12_PM.txt',
  datetime.datetime(2021, 11, 23, 18, 11, 12)],
 ['1',
  '23-11-2021_06-29-02_PM.txt',
  datetime.datetime(2021, 11, 23, 18, 29, 2)],
 ['1',
  '23-11-2021_07-22-35_PM.txt',
  datetime.datetime(2021, 11, 23, 19, 22, 35)],
 ['1',
  '23-11-2021_08-51-45_PM.txt',
  datetime.datetime(2021, 11, 23, 20, 51, 45)],
 ['1',
  '23-11-2021_09-09-32_PM.txt',
  datetime.datetime(2021, 11, 23, 21, 9, 32)]]

In [85]:
dates_df=pd.DataFrame(dates, columns=['folder','filename','timestamp'])
dates_df[:5]

  folder                    filename           timestamp
0      1  23-11-2021_06-11-12_PM.txt 2021-11-23 18:11:12
1      1  23-11-2021_06-29-02_PM.txt 2021-11-23 18:29:02
2      1  23-11-2021_07-22-35_PM.txt 2021-11-23 19:22:35
3      1  23-11-2021_08-51-45_PM.txt 2021-11-23 20:51:45
4      1  23-11-2021_09-09-32_PM.txt 2021-11-23 21:09:32

In [86]:
dates_df['filename'].unique().size

50

In [87]:
l[:5]

['trash/1\\23-11-2021_06-11-12_PM.txt',
 'trash/1\\23-11-2021_06-29-02_PM.txt',
 'trash/1\\23-11-2021_07-22-35_PM.txt',
 'trash/1\\23-11-2021_08-51-45_PM.txt',
 'trash/1\\23-11-2021_09-09-32_PM.txt']

In [88]:
# info=pd.DataFrame(columns=[])

In [94]:
with open("test1.txt", "a") as myfile:
    for i in range(len(l)):
        with open(''.join(l[0]), 'r' ) as result:
            for line in result:
#                            [папка, название, данные . . . . .]
                myfile.write(str(l[i][8:]) + ' ' + line+ '\n')

In [95]:
df=pd.read_csv('test1.txt', sep=' ',header=None, names=['filename','bool','centerX','centerY','width','height'])
df.loc[df['filename']== '24-11-2021_11-43-15_AM.txt']

                       filename  bool   centerX   centerY     width    height
120  24-11-2021_11-43-15_AM.txt     0  0.553745  0.391042  0.037552  0.066324
121  24-11-2021_11-43-15_AM.txt     0  0.582331  0.401167  0.039005  0.067611
122  24-11-2021_11-43-15_AM.txt     1  0.645068  0.421236  0.044615  0.075009
123  24-11-2021_11-43-15_AM.txt     0  0.623669  0.395750  0.040172  0.085778
124  24-11-2021_11-43-15_AM.txt     0  0.609740  0.412801  0.034521  0.068917
370  24-11-2021_11-43-15_AM.txt     0  0.553745  0.391042  0.037552  0.066324
371  24-11-2021_11-43-15_AM.txt     0  0.582331  0.401167  0.039005  0.067611
372  24-11-2021_11-43-15_AM.txt     1  0.645068  0.421236  0.044615  0.075009
373  24-11-2021_11-43-15_AM.txt     0  0.623669  0.395750  0.040172  0.085778
374  24-11-2021_11-43-15_AM.txt     0  0.609740  0.412801  0.034521  0.068917